### ISSUE TITLE
bug(validation): "repository" value format

### ISSUE THREAD

**Issue by Kristinita** [generate/generate-package#11]
### 1. Summary

If I generate `package.json` use generate-package:

    I get incorrect value of `"repository"` parameter.

### 2. Argumentation

See examples from [**official npm docs**](https://docs.npmjs.com/files/package.json#repository):

```json
"repository" :
  { "type" : "git"
  , "url" : "https://github.com/npm/npm.git"
  }
```

```json
"repository": "github:user/repo"
```

But not:

```json
"repository": "user/repo",
```

### 3. Environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Node.js 9.6.0,
+ generate 0.14.0.

### 4. Steps to reproduce

I install generate and generate-package → I create blank folder `D:\SashaDemoRepositories\SashaNpmInitVsGeneratePackage` → I run `gen package` command:

```shell
D:\SashaDemoRepositories\SashaNpmInitVsGeneratePackage>gen package
[09:59:35] starting generate
[09:59:44] √ running tasks: [ 'package' ]
[09:59:47] starting package
? Project description? Demo generate-package
? Author's name? Sasha Chernykh
? Author's URL? https://vk.com/hair_in_the_wind
[10:00:13] finished package √ 26s
```

I get `package.json`:

```json
{
  "name": "SashaNpmInitVsGeneratePackage",
  "description": "Demo generate-package",
  "version": "0.1.0",
  "homepage": "https://github.com/Kristinita/SashaNpmInitVsGeneratePackage",
  "author": "Sasha Chernykh (https://vk.com/hair_in_the_wind)",
  "repository": "Kristinita/SashaNpmInitVsGeneratePackage",
  "bugs": {
    "url": "https://github.com/Kristinita/SashaNpmInitVsGeneratePackage/issues"
  },
  "license": "MIT",
  "engines": {
    "node": ">=4"
  },
  "scripts": {
    "test": "mocha"
  },
  "keywords": [
    "SashaNpmInitVsGeneratePackage"
  ]
}
```

### 5. Expected behavior

```json
"repository": "github:Kristinita/SashaNpmInitVsGeneratePackage",
```

### 6. Actual behavior

```json
"repository": "Kristinita/SashaNpmInitVsGeneratePackage",
```

Thanks.

**Comment by rbecheras** [comment]
Hi again @Kristinita,

The official npm docs you linked 

> https://docs.npmjs.com/files/package.json#repository

is not very explicit but it gives an example (the first: `npm/npm` which will be linked to 
https://github.com/npm/npm.git) in which the default value of the git platform is set to `github` if no any platform is given.

> For GitHub, GitHub gist, Bitbucket, or GitLab repositories you can use the same shortcut syntax you use for npm install:
>
>    "repository": "npm/npm"
>     "repository": "github:user/repo"
>     "repository": "gist:11081aaa281"
>     "repository": "bitbucket:user/repo"
>     "repository": "gitlab:user/repo"

The docs should be more explicit explaining the default host is github.

However, should we be more explicit in our generator to explicit the host in the package file ?
We could so. But we do not have to.

I think a better improvement should be to allow user to select the git platform he would want to use, using github as default selected value.
In fact it is the choice I did in my other generator: [`generate-swap-project`](https://github.com/sirap-group/generate-swap-project)

**Comment by Kristinita** [comment]
@rbecheras, if GitHub — default host and information from npm docs not very explicit, maybe would be nice add this information to generate-package README, that another users don't create similar issues?

Thanks.

**Comment by rbecheras** [comment]
Instead of adding a such note in the readme, I suggested an update to the npm documentation:

> https://github.com/npm/www/issues/318

**Comment by rbecheras** [comment]
The npm docs project has accepted it as a new issue: https://github.com/npm/docs/issues/973
