### ISSUE TITLE
utils.choose is not a function

### ISSUE THREAD

**Issue by tunnckoCore** [generate/generate-package#2]
missing gulp-choose-files maybe? :)

``` sh
% ❯ gen package:choose                                                                                   July 17, 03:34:43
[03:35:06] starting generate
[03:35:07] ✔ running tasks: [ 'package:choose' ]
[03:35:08] starting package 
TypeError: utils.choose is not a function
    at Task.fn (/home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate-package/generator.js:82:19)
```

**Comment by jonschlinkert** [comment]
Do `npm cache clean && npm i -g generate` then try again.

**Comment by tunnckoCore** [comment]
I started from clean node and npm install and did the cleaning before started looking around you latest updates from these 3-4 days.

``` sh
% ❯ gen --version                                                                                          July 17, 03:41:22
[04:53:36] starting generate
generate v0.9.8
```

**Comment by jonschlinkert** [comment]
it's [this](https://github.com/generate/generate-package/blob/master/generator.js#L82). I don't know why I was thinking that https://github.com/generate/generate-package/blob/master/utils.js#L12 was that method. I must have accidentally removed `gulp-choose-files`. Sorry for the confusion
