### ISSUE TITLE
Redundant "files" items

### ISSUE THREAD

**Issue by jamen** [generate/generate-package#9]
This is low-priority, as it doesn't really break anything.

Sometimes when generating, I will see `LICENSE` or `README.md` (assuming `CHANGELOG` too) inside of the `"files"` property inside my `package.json`.  To me, this is noise, because [npm always includes these regarldess](https://docs.npmjs.com/files/package.json#files).

**Comment by jonschlinkert** [comment]
hmm, I thought i removed those a long time ago. thanks for the heads  up

**Comment by jonschlinkert** [comment]
Oh, I know why I didn't notice... I run `update` on every project as soon as it's generated, which formats every file the way I want it regardless of how the generator output the files. 

anyway, I'll get this fixed here, unless you'd like to do a pr. thanks

**Comment by jamen** [comment]
Sure I could PR it if you want.  But it be longer cuz I need to learn these APIs better.

Where is the code  for `files` kept at? I couldn't find anything related in this repo's source.  Unless I am just supposed to add code that removes entries?
